### ISSUE TITLE
[Open3D INFO]skipping non-triangle primitive geometry of type:2

### ISSUE THREAD

**Issue by rain2050** [pengpeng-yu/FastPCC#1]
Thank you for your excellent open source work, but when I run the training code according to the training code you gave, it keeps prompting "[Open3D INFO]skipping non-triangle primitive geometry of type: 2". What is the reason? Have you encountered similar problems? Or know what causes it? Looking forward to your reply.

**Comment by pengpeng-yu** [comment]
Thanks for you attention! It is a texture loading issue of Open3D and can be safely ignored for geometry compression. After your first training, voxelized point clouds of ShapeNet are cached for further use, thereby avoiding the issue of mesh loading.

**Comment by rain2050** [comment]
Thank you very much for your reply
